export * from './HomePage';
export * from './SettingsPage';
export * from './LoginPage';
export * from './ArmasPage';
export * from './C4DashboardPage';
export * from './DashboardPage';
export * from './DetailWeaponPage';
export * from './AmmunitionPage';
export * from './TrainingPage';